name: Todo-List-Proj

on:
  push:
    branches:
      - development
 
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.100-preview.3
        
    - name: Restore dependencies
      run : dotnet restore TodoList.sln
      
    - name: build project
      run: dotnet build --configuration Debug
      
    - name: Run Test
      run: dotnet test --verbosity normal
      
      
    - name: build tests
      run : dotnet test TodoList.sln --no-build --verbosity normal
      
